### PR TITLE
add support for Fast HTML Parser

### PR DESCRIPTION
**Pull request by leeoniya**
hey @nrkn 

i've made some small changes to support this fast and lightweight jsdom alternative: https://www.npmjs.com/package/node-html-parser

i'm using these modifications successfully in my project: https://github.com/leeoniya/dropcss

i'd prefer not to maintain my own fork or keep a modified copy in the `dropcss` repo, so if you merge these changes and publish to npm, i'll be able to simply use it as a dependency.

all the mocha tests still pass.

thanks for your work, too :)

### CODE REVIEW

**Comment by nrkn** [comment]
@leeoniya published - thank you!

**Comment by nrkn** [comment]
Oh hey I just realised, I use dropcss in one of my projects

**Comment by leeoniya** [comment]
thanks!

> Oh hey I just realised, I use dropcss in one of my projects

are you sure it's the same project? the initial release was only 5 days ago:

https://github.com/leeoniya/dropcss/releases/tag/0.1.0

**Comment by nrkn** [comment]
Ah - you're right, I'm using something else - will have to look into dropcss then!

**Pull request merged**
